usage:
  software-stack-deployment: 
    conda: true 
  report: true # add this to confirm that the workflow allows to use 'snakemake --report report.zip' to generate a report containing all results and explanations